version: '3.8'

services:
  ssti-lab:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    restart: unless-stopped
    container_name: ssti-vulnerable-lab
    networks:
      - ssti-network

networks:
  ssti-network:
    driver: bridge
